name: "S3-ECS-Terraform"

on:
  push:
    branches: [main]

jobs:
  s3:
    name: AWS S3 Sync
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-northeast-2"
      BUCKET_NAME: "testbucketforskkuding"

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v4
      - name: AWS Test
        run: aws --version
      
      # AWS 인증 By OpenID Connect
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_FOR_DEPLOY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: S3 Upload
        run: |
          aws s3 sync ./assets s3://${{ env.BUCKET_NAME }}/
