name: "S3-ECS-Terraform"

on:
  push:
    branches: [main]

jobs:
  s3:
    name: AWS S3 Sync
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-northeast-2"
      BUCKET_NAME: "testbucketforskkuding"

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v4
      - name: AWS Test
        run: aws --version
      
      # AWS 인증 By OpenID Connect
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_FOR_DEPLOY }}
          aws-region: ${{ env.AWS_REGION }}
      # S3 Upload
      - name: S3 Upload
        run: |
          aws s3 sync ./assets s3://${{ env.BUCKET_NAME }}/

  ecs:
    name: Update ECS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: "ap-northeast-2"
      ECR_REPOSITORY: "586817503711.dkr.ecr.ap-northeast-2.amazonaws.com/ecr_test"
    
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v4

      # AWS 인증 By OpenID Connect
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_FOR_DEPLOY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login
      - name: Build, Tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest ./node
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:latest"
      
